name: smart_bin
description: A new Flutter project.
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  http: ^0.13.6
  flutter_dotenv: ^5.0.2
  google_maps_flutter: ^2.2.0
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  firebase_core: ^2.12.0    # added
  firebase_auth: ^4.6.0    # add if AuthService uses Firebase Auth

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true